# Generated by Django 5.0 on 2023-12-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0002_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="dishes",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
