# Generated by Django 5.0 on 2023-12-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0005_alter_dish_description_alter_dish_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="dish_type",
        ),
        migrations.AddField(
            model_name="dish",
            name="dish_type",
            field=models.ManyToManyField(related_name="dishes", to="kitchen.dishtype"),
        ),
    ]
