# Generated by Django 4.2.2 on 2024-01-07 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0006_remove_dish_dish_type_dish_dish_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
    ]
